---
- hosts: nstlnxans.westeurope.cloudapp.azure.com
  vars:
    resource_group: blogengine-rg
    location: westeurope
    webapp: nstblogengine
    webappplan: nstblogengineappplan
    mysqlserver_name: nstmysqlserverblog
    mysqldb_name: nstblogeninge
    admin_username: mysqladmin
    admin_password: Testpasswordxyz12!
  tasks:
    - name: Create Resource Group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
      register: rg
    - debug:
        var: rg

    - name: Create Webapp and Plan
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp }}"
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ webappplan }}"
          sku: F1
          is_linux: false
          frameworks:
            - name: net_framework
              version: 4.0
      register: webapp2
    - debug:
        var: webapp2
    - name: Create MySQL Server
      azure_rm_mysqlserver:
        resource_group: "{{ resource_group }}"
        name: "{{ mysqlserver_name }}"
        sku:
          name: B_Gen5_1
          tier: Basic
        location: "{{ location }}"
        version: "5.7"
        enforce_ssl: True
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        storage_mb: 51200
    - name: Create instance of MySQL Database
      azure_rm_mysqldatabase:
        resource_group: "{{ resource_group }}"
        server_name: "{{ mysqlserver_name }}"
        name: "{{ mysqldb_name }}"
    - name: Get WebApp INfo
      azure_rm_webapp_info:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp }}"
      register: webapp3
    - debug:
        msg: "{{ webapp3.webapps[0].outbound_ip_addresses }}"
    - set_fact:
        ips: "{{ webapp3.webapps[0].outbound_ip_addresses.split(',') }}"
    - debug:
        msg: "{{ ips.0 }}-{{ ips.1 }}-{{ ips.2 }}-{{ ips.3 }}"
    - name: Create Webapp Firewall Rules
      azure_rm_mysqlfirewallrule:
        name: "WebappIp{{ ipindex }}-{{ item | replace('.','') }}"
        resource_group: "{{ resource_group }}"
        server_name: "{{ mysqlserver_name  }}"
        start_ip_address: "{{ item }}"
        end_ip_address: "{{ item }}"
      loop: "{{ ips }}"
      loop_control:
        index_var: ipindex
      
