---
- hosts: localhost
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: ansibleawx-test-rg
        location: westeurope
      register: rg
    - debug:
        var: rg
