---
- hosts: 52.174.90.170
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: ansibleawx-rg
        location: westeurope
      register: rg
    - debug:
        var: rg
