---
- hosts: nstlnxans.westeurope.cloudapp.azure.com
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: ansibleawx-rg
        location: westeurope
      register: rg
    - debug:
        var: rg
