---
- hosts: nstlnxans.westeurope.cloudapp.azure.com
  vars:
    resource_group: hybrid-rg
    location: westeurope
    webapp: nsthybridwebapp
    webappplan: nsthybridwebappplan
    mysqlserver_name: nstmysqlserveransible
    mysqldb_name: nstmysqldbansible
    admin_username: mysqladmin
    admin_password: Testpasswordxyz12!
  tasks:
    - name: Get WebApp INfo
      azure_rm_webapp_info:
        resource_group: "{{ resource_group }}"
        name: "{{ webapp }}"
      register: webapp3
    - debug:
        msg: "{{ webapp3.webapps[0].outbound_ip_addresses }}"
    - set_fact:
        ips: "{{ webapp3.webapps[0].outbound_ip_addresses.split(',') }}"
    - debug:
        msg: "{{ ips.0 }}-{{ ips.1 }}-{{ ips.2 }}-{{ ips.3 }}"
    - name: Create Mysql Firewall Rules
      azure_rm_mysqlfirewallrule:
        name: "AllowAll"
        resource_group: "{{ resource_group }}"
        server_name: "{{ mysqlserver_name  }}"
        start_ip_address: "0.0.0.0"
        end_ip_address: "255.255.255.255"
    - name: Create Webapp Firewall Rules
      azure_rm_mysqlfirewallrule:
        name: "{{ (Allow + item) | replace('.','') }}"
        resource_group: "{{ resource_group }}"
        server_name: "{{ mysqlserver_name  }}"
        start_ip_address: "{{ item }}"
        end_ip_address: "{{ item }}"
      loop: "{{ ips }}"
